---
- name: Create Mastodon directory
  become: true
  ansible.builtin.file:
    path: "{{ fb_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true
    state: directory

- name: Configure compose
  become: true
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ fb_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  vars:
    database_ip: "{{ couchdb_ip }}"
    frontback_ip: "{{ frontback_ip }}"

- name: Run docker compose
  become: true
  community.docker.docker_compose:
    project_src: "{{ fb_dir }}"
    pull: true
    state: present
    remove_orphans: true
    recreate: always
