# Common vars
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: MRC_MSTD_CRAWLER
instance_flavor: uom.mse.1c4g

# Security group
security_groups:
  - name: ssh
  - name: http
  - name: default


