---
- name: Create Mastodon directory
  become: true
  ansible.builtin.file:
    path: "{{ mc_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true
    state: directory

- name: Configure compose
  become: true
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ mc_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  vars:
    database_ip: "{{ couchdb_ip }}"

- name: Run docker compose
  become: true
  community.docker.docker_compose:
    project_src: "{{ mc_dir }}"
    pull: true
    state: present
    remove_orphans: true
    recreate: always
