---
volumes:
  - device: /dev/vdb
    mountpoint: /mnt
  # - device: /dev/vdc
  #   mountpoint: /data

mc_dir: mastodon

# Wordpress / MySQL
# database_name: wordpress
# database_user: wordpress
# database_password: wordpress
# mysql_root_password: "P@ssw0rd"
